name: pet_shop
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3

  badges: ^3.1.2
  introduction_screen: ^3.1.14
  sms_otp_auto_verify: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_rating_bar: ^4.0.1
  intl_phone_field: ^3.2.0
  sms_autofill: ^2.4.0
  shared_preferences: ^2.2.3

  #Camera
  # image_cropper: ^7.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  camera: ^0.11.0+1
  oktoast: ^3.4.0
  # path: ^1.9.0
  path_provider: ^2.1.3
  # image_gallery_saver: ^2.0.3
  # gallery_saver: ^2.3.2
  syncfusion_flutter_sliders: ^26.1.39
  flutter_widget_from_html: ^0.15.1
  intl: ^0.19.0
  #Api
  http:
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.9
  flutter_secure_storage:

  #Loading
  shimmer: ^3.0.0
  get: ^4.6.6
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  fluttertoast: ^8.0.9
  fan_carousel_image_slider: ^1.0.1
  #
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Grid layout
  flutter_layout_grid: ^1.0.6 # kiểm tra phiên bản mới nhất

  # Video player
  # chewie: ^1.0.0 # kiểm tra phiên bản mới nhất
  #Slidable
  flutter_slidable: ^3.1.1
  flutter_easyloading: ^3.0.5

  #Readmore
  readmore: ^3.0.0
  sprintf: ^7.0.0
  crypto: ^3.0.3
  flutter_zalopay_sdk:
  onesignal_flutter: ^5.2.2

  # Drop down
  dropdown_button2: ^2.3.9
  # Make a call
  url_launcher: ^6.3.0
  # flutter_phone_direct_caller: ^2.1.1
  # Share
  share_plus: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/_project/Logo/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/_project/Account/
    - assets/images/_project/Predict/
    - assets/images/_project/Home/
    - assets/images/_project/Icons/
    - assets/images/_project/Icons/Frame/
    - assets/images/_project/Icons/Filter/
    - assets/images/_project/Logo/
    - assets/images/_project/Logo/social/
    - assets/images/_project/On_Boarding/
    - assets/images/_project/Payment/
    - assets/images/_project/Plash_Screen/
    - assets/images/_project/Products/
